version: '3.3'
services:
  mysdb:
    image: mysql:5.7
    container_name: "mysql"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ASDqwe123
    network_mode: jenkins   
    ports:
       - "3309:3306"
    volumes:
       - /home/Exadel/MyProject/MyProject/task5/mysql/mysql_db:/var/lib/mysql
       - /home/Exadel/MyProject/MyProject/task5/mysql/files:/var/lib/mysql-files
  slavedb:
    image: mysql:5.7
    container_name: "slave"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ASDqwe123
    network_mode: jenkins
    ports:
      - "3308:3306"
    volumes:
      - /home/Exadel/MyProject/MyProject/task5/mysql/mysql-slave/mysql-db:/var/lib/mysql
