version: '3.3'
services:
  mysdb:
    image: mysql:5.7
    container_name: "mysql_env"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ASDqwe123
       USERNAME: 18 
    network_mode: jenkins
    ports:
       - "3305:3306"
    volumes:
       - /home/Exadel/MyProject/MyProject/task5/mysql/mysql_db:/var/lib/mysql
       - /home/Exadel/MyProject/MyProject/task5/mysql/files:/var/lib/mysql-files
