version: '3'
services:
   web:
    image: chekh87/task2:v6
    deploy:
      mode: replicated
      replicas: 5
   db:
    image: postgres:13.1-alpine
    container_name: db
    ports:
     - 5432:5432
   app:
    image: jenkins:2.60.3-alpine
    container_name: app
    depends_on:
     - db
    ports:
     - 8080:8080
     - 50000:50000
